<a href="https://colab.research.google.com/github/Amrit489/Amrit489.github.io/blob/main/Assignment_4_CC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like:
a) Addition of 2 in all the element
b) Multiply 3 with all the elements
c) Divide every element by 2

In [7]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])

arr1_add = arr1 + 2
print(arr1_add)

arr1_mul=arr1*3
print(arr1_mul)

arr2 = np.array([2,4,6,8,10])
arr2_div=arr2/2
print(arr2_div)

[3 4 5 6 7]
[ 3  6  9 12 15]
[1. 2. 3. 4. 5.]


Q.2 Questions on Basic NumPy Array:
a) ReversetheNumPyarray:arr=np.array([1,2,3,6,4,5])
b) Find the most frequent value and their indice(s)in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [9]:
import numpy as np

arr_Rev = np.array([1, 2, 3, 6, 4, 5])
arr_Rev_reversed = arr_Rev[::-1]
print(arr_Rev_reversed)

x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

most_frequent_x = np.bincount(x).argmax()
indices_x = np.where(x == most_frequent_x)[0]
print(indices_x)

most_frequent_y = np.bincount(y).argmax()
indices_y = np.where(y == most_frequent_y)[0]
print(indices_y)

[5 4 6 3 2 1]
[0 5 7 8 9]
[0 1 2]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access elements using row and column indices as follows:
a) Access1strow,2ndcolumn b) Access3rdrow,1stcolumn

In [9]:
import numpy as np

arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

arr[0:1,1:2]

arr[2:,0:1]

array([[70]])

Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, shape, total elements, the data type of each element and total number of bytes consumed by the array. Find the transpose of this array using reshape() attribute. Can we do the same with T attribute?

In [10]:
import numpy as np

Amrit= np.linspace(10,100,25)

print(Amrit)
print(Amrit.shape)

print(Amrit.size)

print(Amrit.dtype)


print(Amrit.reshape(25,1))

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
(25,)
25
float64
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>> with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, median, max, min, unique elements. Reshape the array to four rows and three columns and name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three columns and name it as resized_ ucs420_<your_name>>.

In [14]:
import numpy as np
ucs420_Amrit=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print(ucs420_Amrit)

mean_value = np.mean(ucs420_Amrit)
print(mean_value)

med_value = np.median(ucs420_Amrit)
print(med_value)

max_value = np.max(ucs420_Amrit)
print(max_value)

min_value = np.min(ucs420_Amrit)
print(min_value)

uni_elements = np.unique(ucs420_Amrit)
print(uni_elements)

reshaped_ucs420_Amrit=ucs420_Amrit.reshape(4,3)
print(reshaped_ucs420_Amrit)

[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
43.333333333333336
37.5
90
10
[10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
